# permissions for end users to view municipalities.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: municipalities-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator-municipalities
    app.kubernetes.io/part-of: operator-municipalities
    app.kubernetes.io/managed-by: kustomize
  name: municipalities-viewer-role
rules:
- apiGroups:
  - municipality.municipalities.rvig
  resources:
  - municipalities
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - municipality.municipalities.rvig
  resources:
  - municipalities/status
  verbs:
  - get
